# Generated by Django 5.0.1 on 2024-01-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdString',
            new_name='ScrapingTask',
        ),
    ]
