# Generated by Django 5.0.1 on 2024-01-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_rename_idstring_scrapingtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_before_discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='savings_percent',
        ),
    ]
